FROM node:20-alpine AS builder
WORKDIR /app
COPY . .
RUN npm install
RUN cd packages/shared && npm run build
RUN cd client && npm run build

FROM nginx:alpine
COPY --from=builder /app/client/dist /usr/share/nginx/html
COPY nginx.client.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
