FROM node:20-alpine
WORKDIR /app
COPY . .
RUN npm install
RUN cd packages/shared && npm run build
RUN cd server && npx prisma generate && npm run build
EXPOSE 3001
CMD ["node", "server/dist/index.js"]
